web:
  image: loomio/loomio:docker
  env_file: ./env
  ports:
    - 80:3000
    - 443:9292
  links:
    - db:db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./uploads:/loomio/whereveruploadsgo
    - ./certificates:/certificates

db:
  image: postgres
  volumes:
    - ./pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

mailin:
  image: loomio/mailin-docker:latest
  links:
    - web:web
  environment:
    - WEBHOOK_URL=http://web:3000/email_processor/

faye:
  image: loomio/loomio-faye
  env_file: ./env
  ports:
    - 4443:4443
