web:
  image: loomio/loomio
  env_file: ./env
  ports:
    - 80:3000
    - 443:9292
  links:
    - db:db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./attachments:/loomio/public/system/attachments
    - ./certificates:/certificates

worker:
  image: loomio/loomio
  env_file: ./env
  links:
    - db:db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./attachments:/loomio/public/system/attachments
    - ./certificates:/certificates
  command: "bundle exec rake jobs:work"

db:
  image: postgres
  volumes:
    - ./pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

mailin:
  image: loomio/mailin-docker
  ports:
    - "25:25"
  links:
    - web:web
  environment:
    - WEBHOOK_URL=http://web:3000/email_processor/

faye:
  image: loomio/loomio-faye
  env_file: ./env
  ports:
    - "4443:4443"
  volumes:
    - ./certificates:/certificates
