app:
  image: loomio/loomio:docker
  env_file: ./config/env
  ports:
    - 80:3000
  links:
    - db:db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./uploads:/loomio/whereveruploadsgo
    - ./certificates:/certificates

db:
  image: postgres
  volumes:
    - ./pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata
