app:
  image: loomio/loomio:docker
  env_file: config/env
  ports:
    - 80:3000
  links:
    - db:db
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
  volumes:
    - ./uploads:/loomio/whereveruploadsgo

db:
  image: postgres
  volumes:
    - ./pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

issue_ssl_cert:
  image: quay.io/letsencrypt/letsencrypt:latest
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./config/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
  command: auth

renew_ssl_cert:
  image: quay.io/letsencrypt/letsencrypt:latest
  ports:
    - 443:443
    - 80:80
  volumes:
    - ./config/letsencrypt:/etc/letsencrypt
    - /var/lib/letsencrypt:/var/lib/letsencrypt
  command: renew
